services:
  - type: web
    name: price-estimator-api
    env: python
    region: oregon
    buildCommand: pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: SERPER_API_KEY
        sync: false
